# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EkList', '0002_auto_20161102_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='minimum_bid',
            field=models.FloatField(default=5.0),
            preserve_default=False,
        ),
    ]
