# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 11:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EkList', '0005_auction_bidders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='version',
        ),
    ]
