# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EkList', '0007_auto_20161105_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='current_bid_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
